import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request';
import BlogCard from '../components/BlogCard';
import Navbar from '../components/Navbar';

const graphcms = new GraphQLClient('https://api-eu-west-2.graphcms.com/v2/cl4479v9t0c1z01z89fo72yhp/master')

const QUERY = gql`
  {
    posts{
      id,
      title,
      datePublished,
      slug,
      content{
        html
      }
      author{
        name
      }
      coverPhoto{
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Real Estate Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1>Estate Articles</h1>
        <div className={styles.blogcard}>
        {posts.map(post => (
          <BlogCard 
            {...post}
            key={post.id}
          />
         ))}
        </div>
        
      </main>
    </div>
  )
}
